### ISSUE TITLE
关于pyts中GASF和GADF无法import

### ISSUE THREAD

**Issue by HiTAndRunaway** [strongnine/Series2Image#1]
如题

**Comment by HiTAndRunaway** [comment]
我已经成功解决 
需要
pip install pyts==0.7.1
打扰了

**Comment by strongnine** [comment]
> 我已经成功解决
> 需要
> pip install pyts==0.7.1
> 打扰了

更新了一下代码，已经能够用最新版本的 pyts （0.11.0） 了。

**Comment by HiTAndRunaway** [comment]
感谢解答！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "strongnine"<notifications@github.com&gt;; 
发送时间: 2020年12月26日(星期六) 下午4:03
收件人: "strongnine/Series2Image"<Series2Image@noreply.github.com&gt;; 
抄送: "UnKnown Programmer"<1750931560@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [strongnine/Series2Image] 关于pyts中GASF和GADF无法import (#1)





  
我已经成功解决
 需要
 pip install pyts==0.7.1
 打扰了
  
更新了一下代码，已经能够用最新版本的 pyts （0.11.0） 了。

**Comment by HiTAndRunaway** [comment]
你好 我还有一个问题 就是我用于处理自己的数据的时候 总是会报如下错误 这个要怎么解决啊
![image](https://user-images.githubusercontent.com/33548408/103511086-53596200-4ea1-11eb-80ef-f3cf2ea23675.png)

**Comment by strongnine** [comment]
> 你好 我还有一个问题 就是我用于处理自己的数据的时候 总是会报如下错误 这个要怎么解决啊
> ![image](https://user-images.githubusercontent.com/33548408/103511086-53596200-4ea1-11eb-80ef-f3cf2ea23675.png)

估计是你的数据里面长度为零了，自己找找看哪里不对吧

**Comment by HiTAndRunaway** [comment]
大佬 我想问一下 通过GADF GASF MTF转换后的图像是灰度图像吗
